version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_manager_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant_manager_database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:17.4
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_DB: restaurant_manager_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


